version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: url_shortener_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: url_shortener_redis
    ports:
      - "6379:6379"

  # kafka:
  #   image: bitnami/kafka:latest
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     - KAFKA_BROKER_ID=1
  #     - KAFKA_LISTENERS=PLAINTEXT://:9092
  #     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #   depends_on:
  #     - zookeeper

  # zookeeper:
  #   image: bitnami/zookeeper:latest
  #   ports:
  # - "2181:2181"

volumes:
  pgdata:
